// Banka otázek pro PxQuiz. k = index správné odpovědi.
const QUESTIONS = [
  { c: "Zeměpis", q: "Které město je hlavním městem Austrálie?", a: ["Sydney", "Canberra", "Melbourne", "Perth"], k: 1 },
  { c: "Zeměpis", q: "Jaké je hlavní město Kanady?", a: ["Toronto", "Vancouver", "Ottawa", "Montreal"], k: 2 },
  { c: "Zeměpis", q: "Jaké je hlavní město Brazílie?", a: ["Rio de Janeiro", "São Paulo", "Salvador", "Brasília"], k: 3 },
  { c: "Zeměpis", q: "Který stát je rozlohou nejmenší na světě?", a: ["Monako", "Vatikán", "San Marino", "Nauru"], k: 1 },
  { c: "Zeměpis", q: "Ve které zemi leží Machu Picchu?", a: ["Bolívie", "Mexiko", "Peru", "Chile"], k: 2 },
  { c: "Zeměpis", q: "Který ostrov je největší na světě?", a: ["Nová Guinea", "Madagaskar", "Grónsko", "Borneo"], k: 2 },
  { c: "Zeměpis", q: "Který oceán je největší?", a: ["Atlantský", "Indický", "Tichý", "Severní ledový"], k: 2 },
  { c: "Zeměpis", q: "Která je největší horká poušť světa?", a: ["Gobi", "Sahara", "Kalahari", "Atacama"], k: 1 },
  { c: "Zeměpis", q: "Ve které zemi stojí Tádž Mahal?", a: ["Pákistán", "Írán", "Indie", "Bangladéš"], k: 2 },
  { c: "Zeměpis", q: "Jaké je hlavní město Norska?", a: ["Bergen", "Oslo", "Stockholm", "Helsinky"], k: 1 },
  { c: "Zeměpis", q: "Ve kterém městě stojí Koloseum?", a: ["Athény", "Neapol", "Řím", "Milán"], k: 2 },
  { c: "Zeměpis", q: "Který stát má nejvíce obyvatel?", a: ["Čína", "Indie", "USA", "Indonésie"], k: 1 },

  { c: "Česko", q: "Jaká je nejvyšší hora Česka?", a: ["Praděd", "Lysá hora", "Sněžka", "Klínovec"], k: 2 },
  { c: "Česko", q: "Ve kterém roce vznikla samostatná Česká republika?", a: ["1989", "1990", "1993", "1995"], k: 2 },
  { c: "Česko", q: "Kdo byl prvním prezidentem Československa?", a: ["Edvard Beneš", "T. G. Masaryk", "Emil Hácha", "Alois Rašín"], k: 1 },
  { c: "Česko", q: "Která řeka protéká Prahou?", a: ["Labe", "Berounka", "Vltava", "Sázava"], k: 2 },
  { c: "Česko", q: "Kdo složil symfonii „Z nového světa“?", a: ["Bedřich Smetana", "Antonín Dvořák", "Leoš Janáček", "Bohuslav Martinů"], k: 1 },
  { c: "Česko", q: "Kdo napsal Osudy dobrého vojáka Švejka?", a: ["Karel Čapek", "Jaroslav Hašek", "Vladislav Vančura", "Bohumil Hrabal"], k: 1 },
  { c: "Česko", q: "Který hrad je podle Guinnessovy knihy největší na světě?", a: ["Karlštejn", "Pražský hrad", "Špilberk", "Bouzov"], k: 1 },
  { c: "Česko", q: "Z jakého slova pochází výraz „robot“, který uvedl Karel Čapek?", a: ["robota", "robustní", "robotník", "rob"], k: 0 },
  { c: "Česko", q: "Které město je druhé největší v Česku?", a: ["Ostrava", "Plzeň", "Brno", "Olomouc"], k: 2 },

  { c: "Věda", q: "Jaká je chemická značka zlata?", a: ["Ag", "Au", "Zl", "Go"], k: 1 },
  { c: "Věda", q: "Který prvek má značku Fe?", a: ["Fosfor", "Fluor", "Železo", "Fermium"], k: 2 },
  { c: "Věda", q: "Který prvek má atomové číslo 1?", a: ["Helium", "Vodík", "Uhlík", "Kyslík"], k: 1 },
  { c: "Věda", q: "Který kov je za pokojové teploty kapalný?", a: ["Rtuť", "Olovo", "Cín", "Draslík"], k: 0 },
  { c: "Věda", q: "Jaká je hlavní složka vzduchu?", a: ["Kyslík", "Oxid uhličitý", "Dusík", "Argon"], k: 2 },
  { c: "Věda", q: "Který plyn rostliny přijímají při fotosyntéze?", a: ["Kyslík", "Oxid uhličitý", "Dusík", "Metan"], k: 1 },
  { c: "Věda", q: "Kdo je autorem teorie relativity?", a: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], k: 2 },
  { c: "Věda", q: "Co měří Richterova škála?", a: ["Sílu větru", "Sílu zemětřesení", "Vlhkost vzduchu", "Hlasitost"], k: 1 },
  { c: "Věda", q: "Který kov nejlépe vede elektrický proud?", a: ["Měď", "Zlato", "Hliník", "Stříbro"], k: 3 },
  { c: "Věda", q: "Jaký je nejtvrdší přírodní materiál?", a: ["Křemen", "Diamant", "Korund", "Titan"], k: 1 },
  { c: "Věda", q: "Kdo byl prvním člověkem ve vesmíru?", a: ["Neil Armstrong", "Alan Shepard", "Jurij Gagarin", "German Titov"], k: 2 },
  { c: "Věda", q: "Která planeta je známá jako Rudá planeta?", a: ["Venuše", "Mars", "Jupiter", "Merkur"], k: 1 },
  { c: "Věda", q: "Která planeta Sluneční soustavy je nejmenší?", a: ["Mars", "Venuše", "Merkur", "Země"], k: 2 },

  { c: "Tělo", q: "Kolik párů žeber má běžně člověk?", a: ["10", "11", "12", "14"], k: 2 },
  { c: "Tělo", q: "Kolik kostí má dospělý člověk?", a: ["186", "206", "226", "256"], k: 1 },
  { c: "Tělo", q: "Který orgán produkuje inzulin?", a: ["Játra", "Slinivka břišní", "Ledviny", "Slezina"], k: 1 },
  { c: "Tělo", q: "Který vitamin si tělo tvoří díky slunečnímu záření?", a: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], k: 2 },

  { c: "Příroda", q: "Které zvíře je největší na Zemi?", a: ["Slon africký", "Plejtvák obrovský", "Vorvaň", "Žralok obrovský"], k: 1 },
  { c: "Příroda", q: "Které suchozemské zvíře je nejrychlejší?", a: ["Gepard", "Antilopa", "Kůň", "Pštros"], k: 0 },
  { c: "Příroda", q: "Kolik nohou má pavouk?", a: ["6", "8", "10", "12"], k: 1 },
  { c: "Příroda", q: "Které zvíře je symbolem organizace WWF?", a: ["Tygr", "Panda velká", "Lední medvěd", "Nosorožec"], k: 1 },
  { c: "Příroda", q: "Které zvíře má nejdelší krk?", a: ["Velbloud", "Pštros", "Žirafa", "Labuť"], k: 2 },

  { c: "Kultura", q: "Kdo namaloval Monu Lisu?", a: ["Michelangelo", "Raffael", "Leonardo da Vinci", "Donatello"], k: 2 },
  { c: "Kultura", q: "Kdo napsal Romea a Julii?", a: ["Charles Dickens", "William Shakespeare", "Molière", "Oscar Wilde"], k: 1 },
  { c: "Kultura", q: "Který nástroj má 88 kláves?", a: ["Varhany", "Klavír", "Cembalo", "Akordeon"], k: 1 },
  { c: "Kultura", q: "Kolik strun mají housle?", a: ["4", "5", "6", "7"], k: 0 },
  { c: "Kultura", q: "Kolik strun má běžná kytara?", a: ["4", "5", "6", "8"], k: 2 },
  { c: "Kultura", q: "Kdo režíroval film Titanic?", a: ["Steven Spielberg", "Ridley Scott", "James Cameron", "Peter Jackson"], k: 2 },
  { c: "Kultura", q: "Kdo nese prsten v Pánu prstenů?", a: ["Aragorn", "Frodo", "Samvěd", "Bilbo"], k: 1 },

  { c: "Historie", q: "Ve kterém roce skončila druhá světová válka v Evropě?", a: ["1943", "1944", "1945", "1946"], k: 2 },
  { c: "Historie", q: "Ve kterém roce padla Berlínská zeď?", a: ["1987", "1989", "1991", "1993"], k: 1 },
  { c: "Historie", q: "Kdo byl prvním člověkem na Měsíci?", a: ["Buzz Aldrin", "Neil Armstrong", "Michael Collins", "John Glenn"], k: 1 },

  { c: "Sport", q: "Kolik hráčů má fotbalový tým na hřišti?", a: ["9", "10", "11", "12"], k: 2 },
  { c: "Sport", q: "Kolik minut trvá jedna třetina v ledním hokeji?", a: ["15", "20", "25", "30"], k: 1 },
  { c: "Sport", q: "Který sport se hraje ve Wimbledonu?", a: ["Kriket", "Golf", "Tenis", "Ragby"], k: 2 },
  { c: "Sport", q: "Která země vyhrála mistrovství světa ve fotbale 2022?", a: ["Francie", "Brazílie", "Argentina", "Chorvatsko"], k: 2 },
  { c: "Sport", q: "Ve kterém městě se konaly odložené LOH 2020?", a: ["Peking", "Paříž", "Tokio", "Rio de Janeiro"], k: 2 },

  { c: "Čísla", q: "Kolik polí má šachovnice?", a: ["36", "49", "64", "81"], k: 2 },
  { c: "Čísla", q: "Kolik je 15 % z 200?", a: ["15", "20", "30", "45"], k: 2 },
  { c: "Čísla", q: "Kolik je odmocnina ze 144?", a: ["11", "12", "13", "14"], k: 1 },
  { c: "Čísla", q: "Kolik dní má přestupný rok?", a: ["364", "365", "366", "367"], k: 2 },
  { c: "Čísla", q: "Kolik teček je celkem na hrací kostce?", a: ["18", "21", "24", "27"], k: 1 },
  { c: "Čísla", q: "Kolik stěn má krychle?", a: ["4", "6", "8", "12"], k: 1 },

  { c: "Technika", q: "Kolik bitů má jeden bajt?", a: ["4", "8", "16", "32"], k: 1 },
  { c: "Technika", q: "Který barevný model se používá pro tisk?", a: ["RGB", "HSL", "CMYK", "YUV"], k: 2 },
  { c: "Technika", q: "Kdo založil Facebook?", a: ["Bill Gates", "Elon Musk", "Mark Zuckerberg", "Jack Dorsey"], k: 2 },
  { c: "Technika", q: "Co znamená zkratka HTML?", a: ["HyperText Markup Language", "High Tech Modern Layout", "Home Tool Markup Logic", "Hyperlink Text Mode Language"], k: 0 },

  { c: "Jídlo", q: "Ve které zemi vznikla pizza?", a: ["Řecko", "Itálie", "Španělsko", "Francie"], k: 1 },
  { c: "Jídlo", q: "Z čeho se kromě vody a kvasnic vaří pivo?", a: ["Chmel a slad", "Réva a cukr", "Kukuřice a sůl", "Brambory a med"], k: 0 },
  { c: "Jídlo", q: "Jaká je měna Japonska?", a: ["Won", "Jüan", "Jen", "Bat"], k: 2 },
  { c: "Jídlo", q: "Jaká je měna Švýcarska?", a: ["Euro", "Švýcarský frank", "Švýcarská koruna", "Marka"], k: 1 }
];
